import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, mkdir, readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import {
  discoverCanonicalSkills,
  syncClaudeSkills,
} from '../../scripts/agents/setup.mjs';

async function createFixture() {
  const root = await mkdtemp(join(tmpdir(), 'applycraft-agents-'));
  const skillDir = join(root, '.agents', 'skills', 'exemplo');
  await mkdir(skillDir, { recursive: true });
  await writeFile(
    join(skillDir, 'SKILL.md'),
    '---\nname: exemplo\ndescription: Executa um fluxo de exemplo.\n---\n\n# Exemplo\n',
  );
  return root;
}

test('descobre skills canônicas e gera adaptadores leves para o Claude', async () => {
  const root = await createFixture();

  assert.deepEqual(
    (await discoverCanonicalSkills(root)).map(({ name, description }) => ({ name, description })),
    [{ name: 'exemplo', description: 'Executa um fluxo de exemplo.' }],
  );

  const result = await syncClaudeSkills({ root });
  const adapter = await readFile(join(root, '.claude', 'skills', 'exemplo', 'SKILL.md'), 'utf8');

  assert.equal(result.skillCount, 1);
  assert.match(adapter, /\.\.\/\.\.\/\.\.\/\.agents\/skills\/exemplo\/SKILL\.md/);
  assert.match(adapter, /Generated by npm run agents:setup/);
  await assert.doesNotReject(syncClaudeSkills({ root, check: true }));
});

test('check detecta adaptador ausente ou desatualizado', async () => {
  const root = await createFixture();

  await assert.rejects(syncClaudeSkills({ root, check: true }), /adaptadores do Claude estão desatualizados/);
});

test('preserva adaptadores que não foram gerados pelo ApplyCraft', async () => {
  const root = await createFixture();
  const adapterDir = join(root, '.claude', 'skills', 'exemplo');
  await mkdir(adapterDir, { recursive: true });
  await writeFile(join(adapterDir, 'SKILL.md'), '# Conteúdo manual\n');

  await assert.rejects(syncClaudeSkills({ root }), /não foi gerado pelo ApplyCraft/);
});
