import { fileURLToPath } from 'node:url';
import { dirname, join, resolve } from 'node:path';
import { mkdir, readFile, readdir, rm, rmdir, writeFile } from 'node:fs/promises';

const scriptDir = dirname(fileURLToPath(import.meta.url));
const defaultRoot = resolve(scriptDir, '../..');
const generatedMarker = '<!-- Generated by npm run agents:setup. Edit the canonical skill under .agents/skills instead. -->';

function unquote(value) {
  const trimmed = value.trim();
  if ((trimmed.startsWith('"') && trimmed.endsWith('"')) || (trimmed.startsWith("'") && trimmed.endsWith("'"))) {
    return trimmed.slice(1, -1);
  }
  return trimmed;
}

function parseFrontmatter(markdown, source) {
  const match = markdown.match(/^---\r?\n([\s\S]*?)\r?\n---/);
  if (!match) throw new Error(`Frontmatter ausente em ${source}`);

  const metadata = {};
  for (const line of match[1].split(/\r?\n/)) {
    const field = line.match(/^([a-zA-Z0-9_-]+):\s*(.+)$/);
    if (field) metadata[field[1]] = unquote(field[2]);
  }

  if (!metadata.name || !metadata.description) {
    throw new Error(`Nome ou descrição ausente em ${source}`);
  }
  return metadata;
}

export async function discoverCanonicalSkills(root = defaultRoot) {
  const skillsDir = join(root, '.agents', 'skills');
  const entries = await readdir(skillsDir, { withFileTypes: true });
  const skills = [];

  for (const entry of entries.filter((item) => item.isDirectory())) {
    const source = join(skillsDir, entry.name, 'SKILL.md');
    let markdown;
    try {
      markdown = await readFile(source, 'utf8');
    } catch (error) {
      if (error.code === 'ENOENT') continue;
      throw error;
    }

    const metadata = parseFrontmatter(markdown, source);
    if (metadata.name !== entry.name) {
      throw new Error(`A skill ${source} declara o nome ${metadata.name}, diferente da pasta ${entry.name}`);
    }
    if (!/^[a-z0-9-]{1,64}$/.test(metadata.name)) {
      throw new Error(`Nome de skill inválido em ${source}: ${metadata.name}`);
    }

    skills.push({ ...metadata, source });
  }

  return skills.sort((left, right) => left.name.localeCompare(right.name, 'pt-BR'));
}

export function renderClaudeAdapter(skill) {
  return `---
name: ${skill.name}
description: ${JSON.stringify(skill.description)}
---

# Adaptador do ApplyCraft

${generatedMarker}

Leia integralmente [a skill canônica](../../../.agents/skills/${skill.name}/SKILL.md) e siga suas instruções. Resolva todos os caminhos relativos a partir da pasta da skill canônica.
`;
}

async function readOptional(path) {
  try {
    return await readFile(path, 'utf8');
  } catch (error) {
    if (error.code === 'ENOENT') return null;
    throw error;
  }
}

export async function syncClaudeSkills({ root = defaultRoot, check = false } = {}) {
  const skills = await discoverCanonicalSkills(root);
  const targetRoot = join(root, '.claude', 'skills');
  const expectedNames = new Set(skills.map((skill) => skill.name));
  const changes = [];

  if (!check) await mkdir(targetRoot, { recursive: true });

  for (const skill of skills) {
    const targetDir = join(targetRoot, skill.name);
    const target = join(targetDir, 'SKILL.md');
    const expected = renderClaudeAdapter(skill);
    const current = await readOptional(target);

    if (current === expected) continue;
    if (current && !current.includes(generatedMarker)) {
      throw new Error(`O adaptador ${target} não foi gerado pelo ApplyCraft e não será sobrescrito`);
    }

    changes.push(target);
    if (!check) {
      await mkdir(targetDir, { recursive: true });
      await writeFile(target, expected, 'utf8');
    }
  }

  let targetEntries = [];
  try {
    targetEntries = await readdir(targetRoot, { withFileTypes: true });
  } catch (error) {
    if (error.code !== 'ENOENT') throw error;
  }

  for (const entry of targetEntries.filter((item) => item.isDirectory() && !expectedNames.has(item.name))) {
    const targetDir = join(targetRoot, entry.name);
    const target = join(targetDir, 'SKILL.md');
    const current = await readOptional(target);
    if (!current?.includes(generatedMarker)) continue;

    changes.push(target);
    if (!check) {
      await rm(target);
      try {
        await rmdir(targetDir);
      } catch (error) {
        if (error.code !== 'ENOTEMPTY') throw error;
      }
    }
  }

  if (check && changes.length > 0) {
    throw new Error('Os adaptadores do Claude estão desatualizados. Execute npm run agents:setup.');
  }

  return { skillCount: skills.length, changes };
}

async function main() {
  const check = process.argv.includes('--check');
  const rootIndex = process.argv.indexOf('--root');
  const root = rootIndex >= 0 ? resolve(process.argv[rootIndex + 1]) : defaultRoot;
  const result = await syncClaudeSkills({ root, check });

  if (check) {
    console.log(`${result.skillCount} adaptadores do Claude estão sincronizados.`);
  } else {
    console.log(`${result.skillCount} adaptadores do Claude disponíveis; ${result.changes.length} alteração(ões) aplicada(s).`);
  }
}

const isMain = process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (isMain) main().catch((error) => {
  console.error(`Não foi possível configurar os agentes: ${error.message}`);
  process.exitCode = 1;
});
